server:
  port: 8087

spring:
  application:
    name: Api-gateway
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    consul:
      host: consul
      port: 8500
      discovery:
        # Each new instance of the service will have unique uuid
        #instance-id: ${spring.application.name}-${server.port}-${random.uuid}
        health-check-path: /actuator/health
        health-check-interval: 10s
        instance-host: 127.0.0.1
        prefer-ip-address: true
        register: true
        enabled: true
    gateway:
      routes:
        - id: messenger_service
          uri: lb://MessengerService
          predicates:
            - Path=/messages/**
        - id: dice_roller_service_route
          uri: lb://diceRollerService
          predicates:
            - Path=/dice/**
        - id: player_character_service
          uri: lb://playerCharacterService
          predicates:
            - Path=/character/**
        - id: campaign_service
          uri: lb://campaignService
          predicates:
            - Path=/campaign/**
        - id: item_service
          uri: lb://ItemsService
          predicates:
            - Path=/items/**
        - id: stats_service
          uri: lb://StatsService
          predicates:
            - Path=/stats/**
        - id: user_service
          uri: lb://userService
          predicates:
            - Path=/users/**
      globalcors:
        cors-configurations:
          '[/**]':
            allowed-origins:
              - "http://localhost:5173"
            allowed-headers:
              - "*"
            allowed-methods:
              - "GET"
              - "POST"
              - "PUT"
              - "DELETE"
              - "OPTIONS"
            allow-credentials: true
  ## MULIG VI TRENGER COORS HER Se bogdan
  ## vi trengte cors

management:
  endpoints:
    web:
      exposure:
        include: health
logging:
  level:
    org.springframework.cloud.loadbalancer: ERROR
    org.springframework.cloud.gateway: ERROR