server:
  port: 8082

spring:
  application:
    name: ItemsService
  cloud:
    consul:
      host: consul
      port: 8500
      discovery:
        # Each new instance of the service will have unique uuid
        instance-id: ${spring.application.name}-${server.port}-${random.uuid}
        health-check-path: /actuator/health
        health-check-interval: 10s
        default-query-tag: http
        prefer-ip-address: true
        register: true
        enabled: true
  datasource:
    #url: jdbc:postgresql://localhost:5432/postgres
    url: jdbc:postgresql://itempostgres:5432/postgres
    username: postgres
    password: postgres
    POSTGRES_DB: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: health