version: '3.8'


services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "15672:15672" # RabbitMQ Management UI
      - "5672:5672"   # RabbitMQ server port
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    depends_on:
      - consul
    networks:
      - dragepust_network
  consul:
    image: hashicorp/consul:1.19.2
    container_name: consul
    ports:
      - "8500:8500/udp"
      - "8500:8500"   # Consul HTTP API
    command: 'agent -dev -node=microExam -client=0.0.0.0 -log-level=ERROR'
    networks:
      - dragepust_network
  dicerollerservice:
    build:
      context: ../diceroller
      dockerfile: Dockerfile
    ports:
      - '8086:8086'
    environment:
      SPRING_PROFILES_ACTIVE: "docker"
    depends_on:
      - consul
      - rabbitmq
    networks:
      - dragepust_network
  messengerservice:
    build:
      context: ../messenger
      dockerfile: Dockerfile
    ports:
      - '8083:8083'
    environment:
      SPRING_PROFILES_ACTIVE: "docker"
    depends_on:
      - consul
      - rabbitmq
    networks:
      - dragepust_network
  playercharacterservice:
    build:
      context: ../playerCharacter
      dockerfile: Dockerfile
    ports:
      - '8081:8081'
    environment:
      SPRING_PROFILES_ACTIVE: "docker"
    depends_on:
      - consul
      - rabbitmq
    networks:
      - dragepust_network
  itemservice:
    build:
      context: ../items
      dockerfile: Dockerfile
    ports:
    - '8082:8082'
    environment:
      SPRING_PROFILES_ACTIVE: "docker"
    depends_on:
      - consul
      - rabbitmq
    networks:
      - dragepust_network








networks:
  dragepust_network:
    driver: bridge