server:
  port : 8081

servicenames:
  itemservice: localhost
  campaignservice: localhost

spring:
  application:
    name: playerCharacterService
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        # Each new instance of the service will have unique uuid
        instance-id: ${spring.application.name}-${server.port}-${random.uuid}
        health-check-path: /actuator/health
        health-check-interval: 10s
        default-query-tag: http
        prefer-ip-address: true
        register: true
        enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5401/postgres
    username: postgres
    password: postgres
    POSTGRES_DB: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    #show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

management:
  endpoints:
    web:
      exposure:
        include: health
